{{- if .Values.ingress.htpasswd.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: mailcatcher-auth-htpasswd
  labels:
    {{- include "mailcatcher.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ printf "%s" (htpasswd .Values.ingress.htpasswd.user .Values.ingress.htpasswd.password) |b64enc }}
{{ end }}
